### ISSUE TITLE
Data type mapping is wrong for numerics

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/power-bi-clickhouse#1]
Power bi is using binary data type for most of numerics

![image](https://github.com/ClickHouse/power-bi-clickhouse/assets/9449405/bad87948-5fae-429c-a30e-e8c81d419485)

Some example of such fix for data type mapping. (It can be done better with table)

https://github.com/UnamedRus/ClickHouseConnectorPowerBI/blob/d4478acb9c31d4f5baffdac9d5234f701ac1b046/Clickhouse.m#L373-L388

**Comment by UnamedRus** [comment]
Also make sense to check this list of issues: https://github.com/belyaevvo/ClickHouseConnector/issues/3#issue-1755793218

**Comment by BentsiLeviav** [comment]
Hi @UnamedRus,

Thank you for bringing this to our attention. I will address the issue and provide updates as we make progress.

Bentsi

**Comment by BentsiLeviav** [comment]
Hi @UnamedRus,

I've updated the types mapping and pushed the changes. We plan to release the new .mez file in the next few days.

Regarding the issues you mentioned:

**Decimal cast bug**

I created a column with decimals and successfully loaded and visualized it. Here's an example:

![image](https://github.com/ClickHouse/power-bi-clickhouse/assets/46030906/c5a135a4-6a96-4093-8477-afeae1970740)


**Filter doesn't work IF only one value is selected**

I loaded the data into PowerBI and tested the filtering functionality. It works as expected, even when only one value is selected. Here are some screenshots for reference:

The entire data:

![image](https://github.com/ClickHouse/power-bi-clickhouse/assets/46030906/f97fb792-9500-49a5-97b8-57d7ed70cb9b)

Filter by one value:

![image](https://github.com/ClickHouse/power-bi-clickhouse/assets/46030906/da3f6bcd-345b-4d31-9360-bd67bcd6c76b)

Filter by multiple values:

![image](https://github.com/ClickHouse/power-bi-clickhouse/assets/46030906/533aa74d-84de-4eb8-96d9-201936d837b2)

Thank you for bringing this to our attention. Please feel free to open any future issues to help us continue improving this connector.

I'll close this issue for now.

Best regards,
Bentsi

**Comment by lgpsouza** [comment]
Hello @BentsiLeviav , how are you?
Have you already updated the .mez file with the correction to correct the numeric data types in directquery mode?

**Comment by BentsiLeviav** [comment]
Hi @lgpsouza 
Yes, the latest mez file contains the changes
