### ISSUE TITLE
Unable to create a connection with an additional connection options.

### ISSUE THREAD

**Issue by ne1r0n** [ClickHouse/power-bi-clickhouse#11]
Connector version: v0.1.2-beta
Power BI Desktop version: 2.123.742.0 64-bit (November 2023)

## How to reproduce:
Specify any valid option in connection options:
For example `Timeout=600`:
`Details: "We cannot convert the value "Timeout=600" to type Record."`

![image](https://github.com/ClickHouse/power-bi-clickhouse/assets/6350825/737dc796-4e66-444c-9c24-ff5dec275f13)
![image](https://github.com/ClickHouse/power-bi-clickhouse/assets/6350825/0af6d740-97bd-44b4-809b-ab4000bf341b)

**Comment by BentsiLeviav** [comment]
Hi @ne1r0n 

We had a problem with converting the ODBC options.
I added a parser handler and validator.

Feel free to share any feedback you may have on #12.
I will add this change to release number 0.1.3-beta.
