### ISSUE TITLE
Connection test fails on app.powerbi.com 

### ISSUE THREAD

**Issue by lucasfcnunes** [ClickHouse/power-bi-clickhouse#15]
### Optional parameters can be necessary to test the connection in Gateway.
In my case, I need `SSLMode=allow` as the test will not work without it. I have to skip the test in order to make it work. Skipping the test everything works as expected on gateway linking and dataset refreshes.

It seems that the following commit may have caused the issue: https://github.com/ClickHouse/power-bi-clickhouse/commit/3bb82c5f23d5857dd0e7e44be2a1bebcdefa8d76

**Comment by BentsiLeviav** [comment]
Hi @lucasfcnunes,
I created a PR to add optional parameters to the test connection handler - #17.

I'm attaching the mez file. could you please approve it solves your problem? (please unzip it first)
[ClickHouse.mez.zip](https://github.com/ClickHouse/power-bi-clickhouse/files/14232887/ClickHouse.mez.zip)

**Comment by BentsiLeviav** [comment]
Hi @lucasfcnunes 
Did you have a chance to check it?

**Comment by BentsiLeviav** [comment]
I'm going to close it for now and merge the changes. 
@lucasfcnunes  Feel free to reopen this if the issue still occurs.

**Comment by lucasfcnunes** [comment]
Thanks, @BentsiLeviav. I will!
