### ISSUE TITLE
Failure to install ClickHouseODBCConnector

### ISSUE THREAD

**Issue by whadley** [ClickHouse/power-bi-clickhouse#16]
I am trying to install the ClickHouseODBCConnector following the instructions in the read me. However when I get to step 5 
`Click on "Get Data" and search for "ClickHouseODBCConnector."`
It does not show up in the get data window.

Any suggestions on how to troubleshoot this?

**Comment by BentsiLeviav** [comment]
Hi @whadley,

Could you please share more info about your problem?

- Power BI version
- Folder path you placed the connector file
- Could you please verify and double-check step 4?

**Comment by vwarda** [comment]
Hello @BentsiLeviav 
Here are the details:
- Version: 2.124.2028.0 64-bit (December 2023)
- Documents\Power BI Desktop\Custom Connectors directory\ClickHouse.mez
- Step 4 was done and powerbi was restarted after.

**Comment by BentsiLeviav** [comment]
@vwarda could you please try to place the mez file in "[Documents]\Microsoft Power BI Desktop\Custom Connectors directory"?
If it still doesn't work, could you please follow [this guide](https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-diagnostics) and upload PowerBI's logs?

**Comment by BentsiLeviav** [comment]
Hi @vwarda, @whadley 
I'm going to close this one, feel free to reopen it if the problem still occurs.
