### ISSUE TITLE
SSL  error

### ISSUE THREAD

**Issue by sladkoejka** [ClickHouse/power-bi-clickhouse#18]
![image](https://github.com/ClickHouse/power-bi-clickhouse/assets/41921144/b14823b7-2a1a-4581-b848-91f2d7d15ca9)

![image](https://github.com/ClickHouse/power-bi-clickhouse/assets/41921144/f5b64e84-949b-4b06-aadb-dbac34f84b8c)
Please tell me how to correctly indicate if I use an SSL certificate?

**Comment by BentsiLeviav** [comment]
Hi @sladkoejka

Based on the path you provided, I understand you use Windows.
As [mentioned in the ODBC connector repo](), the `CALocation` option is ignored in Windows. 
Could you please follow these instructions on how to [add a self-signed certificate in Windows](https://community.spiceworks.com/t/installing-self-signed-ca-certificate-in-windows/1005296)?

**Comment by BentsiLeviav** [comment]
@sladkoejka I'm going to close this for now. Feel free to re-open in case the link provided didn't help.

**Comment by kleinmantara** [comment]
Hi, i have the same problem with the "Power BI Gateway". 

- https://github.com/ClickHouse/clickhouse-odbc
- https://github.com/ClickHouse/power-bi-clickhouse

The Clickhouse driver is added as "User-configured data connectors" and is also displayed as a connection type in Power BI Web. When I then try to add a new "Connection" in Power BI Web, I get the same error message as above:


_Die Verbindung konnte aus folgendem Grund nicht hergestellt werden: Es kann keine Verbindung mit der Datenquelle hergestellt werden. Entweder kann nicht auf die Datenquelle zugegriffen werden, es gab eine Verbindungszeitüberschreibung, oder die Anmeldeinformationen für die Datenquelle sind ungültig. Überprüfen Sie die Datenquellenkonfiguration, und wenden Sie sich zur Problembehandlung an den Administrator der Datenquelle._

_Details: ClickhousePowerBI_Gateway1: **ODBC: ERROR [HY000] Certificate validation error: Failed to verify certificate chain: CA not trusted**_

![image](https://github.com/ClickHouse/power-bi-clickhouse/assets/22788087/c52554fd-2555-4083-85af-e00bee243b6f)
