### ISSUE TITLE
Unable connect to Clickhouse

### ISSUE THREAD

**Issue by hoseiney** [ClickHouse/power-bi-clickhouse#2]
Hi
I can connect to Clickhouse with ODBC but when I want to use the connector, I get this error:
```ODBC: ERROR [HY000] connection refused```

**Comment by Ddolphh** [comment]
Hi,
I get the same error, and also this: ODBC: ERROR [HY000] Timeout

**Comment by lgpsouza** [comment]
I have the same problem, has anyone found a solution?

**Comment by BentsiLeviav** [comment]
Hello,

Thank you for bringing this to our attention.
Could you please provide more information regarding your issue:
- ClickHouse version
- Cloud/on-premise
- Does SSL enabled
- ODBC Driver version installed

Bentsi

**Comment by BentsiLeviav** [comment]
Hi @lgpsouza @Ddolphh @hoseiney,

Upon closer examination, I've identified that the release may not have perfectly aligned with the code in the repository (It's worth noting that this release was initially created during our development phase, which had minor discrepancies).
To ensure everything is running smoothly, I updated the release to include the precise and correct mez file.

Could you please try it and verify that it works for you?

Bentsi

**Comment by lgpsouza** [comment]
Hi, how are you

I tested again with the new update as you requested.

I still get the same error

"Details: "ODBC: ERROR [HY000] Timeout""

**Comment by BentsiLeviav** [comment]
It is a distinct error from the one mentioned in the issue (reported by @hoseiney).

@lgpsouza, in relation to your issue, could you please verify that you have network connectivity from your machine to the ClickHouse server? You can do this by running the following command:

```
curl http://<your_clickhouse_host>:<clickhouse_port>/ping
```
In addition, which PowerBI version and Windows OS do you use?

**Comment by lgpsouza** [comment]
Cool
it worked very well
Really I was trying to connect through the wrong port
Connection worked in Direct query mode
@BentsiLeviav  thank you very much for your help :)

**Comment by lgpsouza** [comment]
I'm using Windows 10 with Power BI version 2.120.963.0 64-bit

**Comment by hoseiney** [comment]
**the connection issue resolved by using new release**

but a new question. how we can write sql query when use direct mode ?

**Comment by lgpsouza** [comment]
Yes, I was able to connect with this new version.

Before that, I cleaned all previous connections on Power Bi and remade the new connection with the updated version.

**Comment by BentsiLeviav** [comment]
Hi all,

I'm delighted to hear that you managed to establish a connection successfully!!

@hoseiney, in response to your query, after loading the data source, you can click on it and select "Edit Query." You will then be prompted to create a custom Power Query. However, please note that if you intend to load an object using a query (as discussed in this [thread](https://community.fabric.microsoft.com/t5/Desktop/Create-custom-query-in-Desktop/m-p/3023645#M1030114)), it is not currently supported.

In any case, I'm closing this issue for now. Please don't hesitate to reach out if you encounter any other issues or have further questions.

Best regards,
Bentsi

**Comment by LvPiShu** [comment]
hi, When I connect to ClickHouse using Power BI, an error occurs: "ODBC: ERROR [HY000] Connection reset by peer"
