### ISSUE TITLE
PowerBI Desktop - Direct Query - Table - Generates invalid nested SQL with overlapping aliases

### ISSUE THREAD

**Issue by GithubUser5462** [ClickHouse/power-bi-clickhouse#20]
**Describe the bug**
Table visualization generates broken SQL. 

**To Reproduce**
In clickhouse create a table with multiple numeric columns (int64, float64) and import it as direct query in powerbi.
In powerbi add a table visualization and add multiple columns to it.
Initially it works fine, but eventually it starts nesting the query and assigning aliases like C1, C2, C3,... which overlap.
This causes errors "aggregate function found inside another aggregate function" and "cyclic alias".

Example of generated query:
```
SELECT sum(CAST(C2, 'DOUBLE')) AS C1, sum(CAST(C1, 'DOUBLE')) AS C2
FROM (SELECT CAST(round(CAST(impressions, 'DOUBLE'), _CAST(0, 'Nullable(Int32)')), 'BIGINT') AS C1, CAST(round(CAST(inviews, 'DOUBLE'), _CAST(0, 'Nullable(Int32)')), 'BIGINT') AS C2 FROM ...
```

### Configuration
* PowerBI version: 2.126.927.0 64-bit (februar 2024)
* power-bi-clickhouse version: v0.1.4-beta
* ClickHouse ODBC driver version: 1.2.1.20220905
* Operating system: Windows 11

**Comment by BentsiLeviav** [comment]
Thank you for your feedback!

Could you be more precise? Did you do something actively before getting this error?
If possible, could you add precise steps to reproduce the issue? I couldn't produce it with your current explanation.

**Comment by UnamedRus** [comment]
https://github.com/ClickHouse/ClickHouse/issues/26674

**Comment by GithubUser5462** [comment]
Got the chance to update my clickhouse instance and it seems to be fixed, thank you.
