### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by bubbaspaarx** [ClickHouse/power-bi-clickhouse#25]
**Describe the bug**
Unable to authenticate with from PowerBi desktop to our clickhouse cloud server 

We receive a message saying that the authentication has failed and either the password is wrong or the user doesn't exist. 

Using the same details on a curl request works absolutely fine so I don't believe the that the password or user details are incorrect. 

**To Reproduce**
1. Enter details for server, database, user and password
2. Try to connect

**Expected behavior**
Expect to connect to our database from PowerBi desktop using the OBDC connector

**Screenshots**

#### Environment
* PowerBI version: latest
* power-bi-clickhouse version: v0.1.5-beta
* ClickHouse ODBC driver version: 1.2.1.20220905
* Operating system: Windows

**Comment by bubbaspaarx** [comment]
FYI to anyone who also got here. This is an issue with '~' tilde's being present in the password. It is also a known issue on the clickhouse side of things.

**Comment by anob1223** [comment]
Could this be related to reports published in PowerBI Service? We are unable to authenticate under "Manage Connections and Gateways" as whenever we are selecting Authentication Type dropdown, it shows blank.

![image](https://github.com/ClickHouse/power-bi-clickhouse/assets/174840017/7d350551-46b5-4d2b-863f-a67c94ab9198)

**Comment by bubbaspaarx** [comment]
> Could this be related to reports published in PowerBI Service? We are unable to authenticate under "Manage Connections and Gateways" as whenever we are selecting Authentication Type dropdown, it shows blank.
> 
> ![image](https://private-user-images.githubusercontent.com/174840017/346237080-7d350551-46b5-4d2b-863f-a67c94ab9198.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NTIwMTMsIm5iZiI6MTcyMDQ1MTcxMywicGF0aCI6Ii8xNzQ4NDAwMTcvMzQ2MjM3MDgwLTdkMzUwNTUxLTQ2YjUtNGQyYi04NjNmLWE2N2M5NGFiOTE5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQxNTE1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmI1ZTU4YWNiZTRlNmVjNTFmZmZjM2E2NGFjYWFhMDBhMDk0ZWVhZjJjN2YwNWZkOTAzMjI2NDhmNDc5OTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7H0Ts_yC-LA4tGoXe7KzROEE6fx0KZ4zaF90n-fdIwA)

Not sure this is linked to our issue as we hadn't been able to get that far but I'll bear it in mind. 
There is apparently an option in the Powerbi settings related to credentials being saved for all connections. This also prevented us from changing the password on a connection we had already set up so it may be related to that.

It's definitely worth doing a live chat with Clickhouse support if you're having issues as this is how we found out about the ~/tilde issue

**Comment by laeg** [comment]
@bubbaspaarx I'm trying to locate the known database issue around using a tilda, do you know where it is. However, I noticed you said you can authenticate with the tilda via curl?

**Comment by BentsiLeviav** [comment]
@bubbaspaarx I created a new user in my CH instance with the following command:
`CREATE USER tildatest IDENTIFIED WITH sha256_password BY 'TildaTest123~';`

and it worked both in PowerBI and HTTP.
Could you add more about your usecase? what `Identification` method did you use when creating the user?

**Comment by bubbaspaarx** [comment]
I can't verify right now unfortunately as I wasn't the person in the organisation who ran into the issue. Powerbi desktop is also only on Windows OS and I'm not using that so I can't even check. 

I'll see if there's anyone else who can try though. 

The other complication is that the password given for the service was automatically generated, so it's not guaranteed the password would contain a ~ either.

**Comment by BentsiLeviav** [comment]
@bubbaspaarx got it.

Since I managed to connect to CH over PowerBI using the user and password mentioned (with Tilda) - I close this issue. Feel free to reopen it if you encounter the issue again.
