### ISSUE TITLE
Connect to ClickHouse from Power BI Service

### ISSUE THREAD

**Issue by golliaph** [ClickHouse/power-bi-clickhouse#3]
Hello!
I can connect to Clickhouse from Power BI Desktop, but receive error when I am trying to connect from Power BI Service. Have you tested connector with power bi gateway? Is there any instructions for this scenario?

**Comment by BentsiLeviav** [comment]
Hi @golliaph,

Thank you for bringing this to our attention. We haven't tested the connector with Power BI service yet. Could you please share the exception you encountered? Additionally, could you provide details on how you added the connector to the service?

Thank you,
Bentsi

**Comment by pshtiwan-hassan** [comment]
Hello,

when i did sum aggrigation for a spsensif column (int64), i received this error message :-


![image](https://github.com/ClickHouse/power-bi-clickhouse/assets/67946816/23045186-6822-4c5e-8282-13c1a1ce3694)

**Comment by UnamedRus** [comment]
It's needed to disable convert in connector.
Something like that could work

https://github.com/UnamedRus/ClickHouseConnectorPowerBI/blob/d4478acb9c31d4f5baffdac9d5234f701ac1b046/Clickhouse.m#L220-L228

**Comment by BentsiLeviav** [comment]
Hi @Avatargen and @golliaph

This issue was discussed in #5 as well, please refer to the solution provided there.

@morSchmidt, @UnamedRus, @pshtiwan-hassan it appears to be a different issue, unrelated to PowerBI service. I've created a separate issue, #9; let's continue our discussion there.
