### ISSUE TITLE
Details about official release and certification

### ISSUE THREAD

**Issue by SteefJanssen1** [ClickHouse/power-bi-clickhouse#35]
Hi Clickhouse team,

**Describe the feature**
It would be helpful to keep the documentation updated with details about the expected timeline for the official (non-beta) release of the Power BI connector and information about certification with Microsoft.

**Why is this feature useful?**
Currently, the blog post at [Official Microsoft Power BI Connector](https://clickhouse.com/blog/official-microsoft-power-bi-connector) does not provide clarity about:
- When the connector is expected to transition from beta to a stable release.
- The timeline or status for obtaining Microsoft certification.

This information is critical for users planning to adopt the connector in production environments.

**Expected behavior**
Include the following in the documentation:
- An estimated timeline or milestone for the official non-beta release.
- Updates on the status of Microsoft certification or a target timeline for completion.

**Additional context**
Keeping this information up-to-date will ensure better transparency and allow users to make informed decisions regarding adoption in enterprise environments.

Many Thanks

**Comment by BentsiLeviav** [comment]
Hi @SteefJanssen1 

As of today, the connector is certified and available within the new PowerBI releases.
Per your question regarding the beta flag, we estimate it to be removed in the next PowerBI release (Dec 2025).
The [docs page in the ClickHouse documentation site](https://clickhouse.com/docs/en/integrations/powerbi) has been updated, we will update this repo readme file shortly.

Feel free to reply for more information.
