### ISSUE TITLE
Conversion error for Int64

### ISSUE THREAD

**Issue by BentsiLeviav** [ClickHouse/power-bi-clickhouse#9]
(moving discussion from #3)
@pshtiwan-hassan and @morSchmidt receive an error when trying to aggregate Integer64 fields. 
![image](https://github.com/ClickHouse/power-bi-clickhouse/assets/46030906/2dc5346c-7688-4b57-ac01-6938c2aed533)

@morSchmidt indicated that this could be reproduced with our [dataset](https://clickhouse.com/docs/en/getting-started/example-datasets/uk-price-paid)
![image](https://github.com/ClickHouse/power-bi-clickhouse/assets/46030906/707067d6-8305-4fba-aa6c-4d6a06b7dc20)

@UnamedRus suggested to disable the conversion on the connector side by doing something [like](https://github.com/UnamedRus/ClickHouseConnectorPowerBI/blob/d4478acb9c31d4f5baffdac9d5234f701ac1b046/Clickhouse.m#L220-L228)

**Comment by eliempje** [comment]
Any update?

**Comment by BentsiLeviav** [comment]
As @UnamedRus pointed out, the issue was that PowerBI's default behavior is to use `CONVERT`, while Clickhouse's conversion method is used by `CAST`. 

I overrode the proper config. PR #13
